/**
 * Vision-LLM describer used by the supervisor loop.
 *
 * Pi-agent is always the judge. This helper just turns an image
 * (path + prompt context) into a plain-text description that pi-agent
 * reads inside a `[SYSTEM EVENT]` message and acts on. Returns null
 * — never throws — when:
 *   - VLM_PROVIDER / VLM_API_KEY / VLM_MODEL aren't set in env. The
 *     first such skip logs ONE warning per process; subsequent skips
 *     are silent so a 200-asset run doesn't spam stderr.
 *   - The underlying call throws (network blip, API error, etc.).
 *     Operational failures are not warned — the missing-config
 *     warning slot is reserved for actually-fixable config errors.
 *
 * The describer is injectable for tests. Default: build an
 * `LLMClient` from `getVLMConfig()` and call `chatWithImage`.
 */
import { LLMClient } from "./LLMClient.js";
import { getVLMConfig } from "./getVLMConfig.js";

export type DescribeImageFn = (
  imagePath: string,
  prompt: string,
) => Promise<string>;

let warned = false;

const DESCRIBE_SYSTEM_PROMPT = `You are a vision encoder feeding a downstream judge.
The judge cannot see the image; it only sees what you describe.
Your job is to produce a description that lets the judge decide
whether the image matches the prompt and whether it is usable.

Cover BOTH:

1. **Visual content — describe in detail.** Subjects (who, doing
   what, in what posture). Setting (where, time of day, weather,
   architecture, props). Composition (framing, camera angle,
   distance, depth, focus). Lighting (key light, shadow direction,
   warmth/coolness, atmosphere). Style cues (photoreal /
   illustrated / painterly, period, mood). Any text or signage
   visible. Be specific — counts, colors, named details. Take as
   many sentences as you need; do not abbreviate.

2. **Significant generation artifacts — flag them.** Look for and
   call out:
   - Anatomical errors: wrong finger count, fused fingers, extra or
     missing limbs, distorted hands/feet, melted faces, mismatched
     eyes, broken teeth, doubled heads.
   - Compositional artifacts: doubled / ghosted subjects,
     impossible perspective, broken lines (architecture, horizons),
     orphaned body parts.
   - Texture / surface artifacts: blurry or blocky regions,
     plastic-skin uncanny smoothness, color banding, oversharpened
     edges, JPEG-style blockiness, posterization.
   - Identity drift in named characters/settings if you can tell.

   Only mention artifacts that are SIGNIFICANT — distracting at
   normal viewing, not pixel-peeping. If the image is clean, say
   "No significant artifacts." Don't invent issues.

Format: plain prose, no preface, no markdown, no bullet points.
Two paragraphs is fine — visual content first, then an artifact
assessment. Length is not the goal; completeness is.`;

function defaultDescriber(): DescribeImageFn | null {
  const config = getVLMConfig();
  if (!config) return null;
  const llm = new LLMClient({
    baseUrl: config.baseUrl,
    apiKey: config.apiKey,
    model: config.model,
  });
  return async (imagePath, prompt) => {
    const userText = `The image was generated by an AI image model from this prompt: "${prompt}"\n\nDescribe what you see in detail, then assess any significant generation artifacts.`;
    return llm.chatWithImage(imagePath, userText, DESCRIBE_SYSTEM_PROMPT, {
      // The detailed description + artifact pass needs more than the
      // default 2000-token cap. 4000 leaves headroom for verbose
      // models without truncating partway through the artifact list.
      maxTokens: 4000,
    });
  };
}

export async function describeImageWithVLM(
  imagePath: string,
  prompt: string,
  describer?: DescribeImageFn,
): Promise<string | null> {
  const fn = describer ?? defaultDescriber();
  if (!fn) {
    if (!warned) {
       
      console.warn(
        "[VLM] VLM_PROVIDER / VLM_API_KEY / VLM_MODEL not set — VLM calls will be skipped. The pi-agent oversight loop runs without vision feedback for asset events.",
      );
      warned = true;
    }
    return null;
  }
  try {
    return await fn(imagePath, prompt);
  } catch {
    // Operational failure — the supervisor will run with
    // `vlm_description: (none)` for this asset. Not config-missing,
    // so don't burn the once-per-process warning.
    return null;
  }
}

/** Test-only — clear the once-per-process warning latch. */
export function __resetVLMWarningForTesting(): void {
  warned = false;
}
