/**
 * `ffmpeg.overlay` — composite an overlay IMAGE onto a base VIDEO at a chosen
 * position/scale. Fully deterministic (ffmpeg overlay filter), so the overlaid
 * pixels are byte-exact after a clean resize — never regenerated/obfuscated by
 * a model. Built for "screen inset / PiP" shots: a talking-head clip with a
 * pixel-exact app screenshot card over it.
 *
 * Config:
 *   - baseInput (string): input id holding the base video path. Falls back to
 *       the first video path found in ctx.inputs.
 *   - overlayInput (string): input id holding the overlay image path. Falls
 *       back to the first image path found in ctx.inputs.
 *   - position: 'top' | 'bottom' | 'center' | 'top-left' | 'top-right' |
 *       'bottom-left' | 'bottom-right'. Default 'top'.
 *   - scale (number): overlay width as a fraction of the base width. Default 0.62.
 *   - margin (number): px inset from the edges. Default 48.
 *   - borderWidth (number): px border drawn around the overlay. Default 0.
 *   - borderColor (string): default 'white'.
 *   - outputPath (string): set by the walker from node.outputs.pattern.
 */
import { existsSync, mkdirSync, statSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { spawn, execFileSync } from 'node:child_process';
import { ffmpegBin, ffprobeBin } from './ffmpegBin.js';
import type { Runner, RunnerContext, RunnerDescription, RunnerResult } from '../schema.js';

type Position =
  | 'top' | 'bottom' | 'center'
  | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';

interface OverlayConfig {
  baseInput?: string;
  overlayInput?: string;
  position?: Position;
  scale?: number;
  margin?: number;
  borderWidth?: number;
  borderColor?: string;
  outputPath?: string;
  forceRerun?: boolean;
}

const IMAGE_RE = /\.(png|jpe?g|webp|gif|bmp)$/i;
const VIDEO_RE = /\.(mp4|mov|webm|mkv|m4v)$/i;

function firstPath(ctx: RunnerContext, re: RegExp, preferKey?: string): string | undefined {
  if (preferKey) {
    const v = ctx.inputs[preferKey];
    if (typeof v === 'string' && re.test(v) && existsSync(v)) return v;
  }
  for (const inp of ctx.node.inputs) {
    const v = ctx.inputs[inp.from];
    if (typeof v === 'string' && re.test(v) && existsSync(v)) return v;
  }
  for (const v of Object.values(ctx.inputs)) {
    if (typeof v === 'string' && re.test(v) && existsSync(v)) return v;
  }
  return undefined;
}

function probeWidth(path: string): number | null {
  try {
    const out = execFileSync(ffprobeBin(), [
      '-v', 'error', '-select_streams', 'v:0', '-show_entries', 'stream=width',
      '-of', 'default=nw=1:nk=1', path,
    ], { encoding: 'utf-8' }).trim();
    const n = parseInt(out, 10);
    return Number.isFinite(n) && n > 0 ? n : null;
  } catch {
    return null;
  }
}

/** Build the overlay filter_complex. Position uses overlay-filter expressions
 *  (main_w/overlay_w …) so only the base WIDTH is needed (for the scale). */
export function buildOverlayFilter(opts: {
  baseWidth: number;
  position: Position;
  scale: number;
  margin: number;
  borderWidth: number;
  borderColor: string;
}): string {
  const { baseWidth, position, scale, margin, borderWidth, borderColor } = opts;
  const ow = Math.max(2, Math.round(baseWidth * scale));
  let ovChain = `[1:v]scale=${ow}:-2`;
  if (borderWidth > 0) {
    ovChain += `,pad=iw+${2 * borderWidth}:ih+${2 * borderWidth}:${borderWidth}:${borderWidth}:${borderColor}`;
  }
  ovChain += `[ov]`;
  const cx = `(main_w-overlay_w)/2`;
  const cy = `(main_h-overlay_h)/2`;
  const m = margin;
  const pos: Record<Position, string> = {
    'top': `${cx}:${m}`,
    'bottom': `${cx}:main_h-overlay_h-${m}`,
    'center': `${cx}:${cy}`,
    'top-left': `${m}:${m}`,
    'top-right': `main_w-overlay_w-${m}:${m}`,
    'bottom-left': `${m}:main_h-overlay_h-${m}`,
    'bottom-right': `main_w-overlay_w-${m}:main_h-overlay_h-${m}`,
  };
  return `${ovChain};[0:v][ov]overlay=${pos[position]}:format=auto[v]`;
}

function runFFmpeg(args: string[]): Promise<{ ok: boolean; stderr: string }> {
  return new Promise((resolveDone) => {
    const proc = spawn(ffmpegBin(), args, { stdio: ['ignore', 'pipe', 'pipe'] });
    let stderr = '';
    proc.stderr?.on('data', (d) => { stderr += d.toString(); });
    proc.on('close', (code) => resolveDone({ ok: code === 0, stderr }));
    proc.on('error', (e) => resolveDone({ ok: false, stderr: `spawn failed: ${e.message}` }));
  });
}

export function createFfmpegOverlayRunner(): Runner {
  const describe = (): RunnerDescription => ({
    id: 'ffmpeg.overlay',
    displayName: 'FFmpeg Overlay',
    description: 'Composites an overlay image onto a base video (PiP / screen inset) deterministically — overlaid pixels are byte-exact after a clean resize, never regenerated by a model.',
    capabilities: ['video-composite', 'overlay', 'pip'],
    modalities: { input: ['video', 'image'], output: ['video'] },
    configSchema: {
      type: 'object',
      required: ['outputPath'],
      properties: {
        baseInput: { type: 'string' },
        overlayInput: { type: 'string' },
        position: { type: 'string' },
        scale: { type: 'number' },
        margin: { type: 'number' },
        borderWidth: { type: 'number' },
        borderColor: { type: 'string' },
      },
    },
  });

  async function run(ctx: RunnerContext): Promise<RunnerResult> {
    const cfg = ctx.node.runner.config as unknown as OverlayConfig;
    if (!cfg.outputPath) return { ok: false, error: 'ffmpeg.overlay: missing outputPath' };

    const basePath = firstPath(ctx, VIDEO_RE, cfg.baseInput);
    if (!basePath) return { ok: false, error: `ffmpeg.overlay: no base video resolved (baseInput='${cfg.baseInput ?? ''}')` };
    const overlayPath = firstPath(ctx, IMAGE_RE, cfg.overlayInput);
    if (!overlayPath) return { ok: false, error: `ffmpeg.overlay: no overlay image resolved (overlayInput='${cfg.overlayInput ?? ''}')` };

    const outAbs = resolve(ctx.projectDir, cfg.outputPath);
    mkdirSync(dirname(outAbs), { recursive: true });
    if (!cfg.forceRerun && existsSync(outAbs) && statSync(outAbs).size > 0 && !process.env['DAG_BUNDLE_FORCE_RERENDER']) {
      ctx.log(`ffmpeg.overlay: ${cfg.outputPath} exists — skipping (set DAG_BUNDLE_FORCE_RERENDER=1 to force)`);
      return { ok: true, outputPath: cfg.outputPath, metadata: { skipped: true, reason: 'output_exists' } };
    }

    const baseWidth = probeWidth(basePath) ?? 768;
    const filter = buildOverlayFilter({
      baseWidth,
      position: cfg.position ?? 'top',
      scale: cfg.scale ?? 0.62,
      margin: cfg.margin ?? 48,
      borderWidth: cfg.borderWidth ?? 0,
      borderColor: cfg.borderColor ?? 'white',
    });

    const args = [
      '-hide_banner', '-loglevel', 'error', '-y',
      '-i', basePath, '-i', overlayPath,
      '-filter_complex', filter, '-map', '[v]', '-map', '0:a?',
      '-c:v', 'libx264', '-preset', 'medium', '-crf', '20', '-pix_fmt', 'yuv420p',
      '-c:a', 'copy', '-movflags', '+faststart', outAbs,
    ];
    ctx.log(`ffmpeg.overlay: ${overlayPath.split('/').pop()} onto ${basePath.split('/').pop()} (${cfg.position ?? 'top'}, scale ${cfg.scale ?? 0.62}) → ${cfg.outputPath}`);
    const r = await runFFmpeg(args);
    if (!r.ok) return { ok: false, error: `ffmpeg.overlay: ffmpeg failed — ${r.stderr.split('\n').slice(-4).join(' ')}` };
    if (!existsSync(outAbs) || statSync(outAbs).size === 0) {
      return { ok: false, error: `ffmpeg.overlay: ffmpeg reported success but ${outAbs} is missing/empty` };
    }
    return { ok: true, outputPath: cfg.outputPath, metadata: { base: basePath, overlay: overlayPath } };
  }

  return { describe, run };
}

export const ffmpegOverlayRunner = createFfmpegOverlayRunner();
