#!/usr/bin/env tsx
/**
 * A/B probe: render the same first-frame image through the LTX 2.3 INT8
 * i2v workflow with two different motion-prompt styles —
 *
 *   A) the existing dhee motion directive (read verbatim from
 *      `<project>/prompts/motion/scene_<S>_shot_<N>.json`, then prefixed
 *      with dhee's auto-prepended preamble exactly as production does)
 *   B) a fresh LTX-V-official-style prompt, generated by DeepSeek via
 *      OpenRouter using the official LTX-V i2v system prompt at
 *      `prompts/probes/ltxv_official_i2v.md`. The user message is built
 *      from the same shot brief that originally drove prompt A, so the
 *      two prompts express the same shot intent in different styles.
 *
 * Both prompts are sent through the workflow JSON at
 * `/Users/ganaraj/Downloads/video_ltx2_3_i2v_int8 (1).json` with only
 * two node overrides:
 *   - node "366" .inputs.value  → prompt text
 *   - node "269" .inputs.image  → uploaded image filename
 *
 * Output: two MP4s in `test-output/` plus a JSON sidecar recording both
 * prompts and the queue ids.
 */

import 'dotenv/config';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, basename } from 'path';
import { ComfyUIClient } from '../src/services/comfyui/ComfyUIClient.js';
import { LLMClient } from '../src/core/llm/LLMClient.js';

const REPO_ROOT = process.cwd();
const WORKFLOW_PATH = '/Users/ganaraj/Downloads/video_ltx2_3_i2v_int8 (1).json';
const LTX_SYSTEM_PROMPT_PATH = join(REPO_ROOT, 'prompts/probes/ltxv_official_i2v.md');

const PROJECT = 'noir_detective_story_setup-3.dhee';
const SCENE = 1;
const SHOT = 5;
const IMAGE_PATH = join(
  REPO_ROOT,
  PROJECT,
  'assets/images/s1shot5_first_frame_klein_-wqp0v.png',
);
const MOTION_PATH = join(
  REPO_ROOT,
  PROJECT,
  `prompts/motion/scene_${SCENE}_shot_${SHOT}.json`,
);
const SHOT_BRIEF_PATH = join(
  REPO_ROOT,
  PROJECT,
  `prompts/videos/scenes/scene_${SCENE}.shots/${SHOT}.json`,
);
const SHOT_IMAGE_PROMPT_PATH = join(
  REPO_ROOT,
  PROJECT,
  `prompts/images/shots/scene-${SCENE}-shot-${SHOT}.json`,
);

const OUTPUT_DIR = join(REPO_ROOT, 'test-output');
const dhee_PREAMBLE = 'Make this image come alive with cinematic motion, smooth animation.';

async function buildPromptB(): Promise<string> {
  const override = process.env['PROMPT_B_OVERRIDE'];
  if (override && override.trim()) {
    console.log('Using PROMPT_B_OVERRIDE (skipping DeepSeek call)');
    return override.trim();
  }
  const systemPrompt = readFileSync(LTX_SYSTEM_PROMPT_PATH, 'utf-8');
  const brief = JSON.parse(readFileSync(SHOT_BRIEF_PATH, 'utf-8'));
  const imgPrompts = JSON.parse(readFileSync(SHOT_IMAGE_PROMPT_PATH, 'utf-8'));
  const firstFrameDescription: string =
    imgPrompts?.frames?.first_frame?.imagePrompt ?? '';

  // DeepSeek v4 flash is text-only, so we surface the first-frame image
  // as a textual description (the same prose that drove the image's
  // generation). The LTX-V system prompt's "Analyze the Image" step then
  // operates over that description instead of pixels.
  const userMessage = [
    'IMAGE DESCRIPTION (first frame already rendered, this is what the model sees):',
    firstFrameDescription,
    '',
    'RAW INPUT PROMPT (the motion the user wants):',
    `${brief.description} Camera: ${brief.cameraWork}. Audio context: ${brief.audio}. Duration: ${brief.duration}s.`,
  ].join('\n');

  const apiKey = process.env['OPENAI_API_KEY']; // sk-or-... OpenRouter key
  if (!apiKey) throw new Error('OPENAI_API_KEY (OpenRouter) not set');

  const llm = new LLMClient({
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKey,
    model: 'deepseek/deepseek-v4-flash',
  });

  console.log('Calling DeepSeek via OpenRouter for LTX-style prompt...');
  const res = await llm.generate({
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userMessage },
    ],
    temperature: 0.7,
    maxTokens: 600,
  });

  let text = (res.content || '').trim();
  if (!text) {
    console.log('DeepSeek returned empty — retrying once with higher temp...');
    const res2 = await llm.generate({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userMessage },
      ],
      temperature: 0.9,
      maxTokens: 600,
    });
    text = (res2.content || '').trim();
  }
  if (!text) throw new Error('DeepSeek returned empty content after retry');
  return text;
}

async function renderOne(
  client: ComfyUIClient,
  workflowTemplate: Record<string, any>,
  promptText: string,
  uploadedImage: string,
  label: 'A' | 'B',
): Promise<string> {
  // Deep clone to avoid mutating the shared template between runs.
  const wf = JSON.parse(JSON.stringify(workflowTemplate));
  wf['366'].inputs.value = promptText;
  wf['269'].inputs.image = uploadedImage;
  wf['75'].inputs.filename_prefix = `probe_${label}_${Date.now()}`;

  console.log(`\n[${label}] Queueing — prompt (${promptText.length} chars)`);
  const queueResult = await client.queueWorkflow(wf, undefined, true);
  console.log(`[${label}] promptId=${queueResult.promptId}`);

  const result = await client.waitForCompletionWS(
    queueResult.promptId,
    queueResult.clientId!,
    info => {
      if (info.percentage > 0) {
        process.stdout.write(`\r  [${label}] ${info.message}`);
      }
    },
  );
  console.log('');
  if (result.status !== 'completed') {
    throw new Error(`[${label}] workflow failed: ${result.status}`);
  }

  const outputs = await client.getOutputImages(queueResult.promptId);
  if (outputs.length === 0) throw new Error(`[${label}] no output files`);
  const first = outputs[0]!;
  const outName = `probe_ltx_${label}_${SCENE}_${SHOT}_${Date.now()}.mp4`;
  const savedPath = await client.downloadImage(
    first.filename,
    first.subfolder,
    first.type,
    outName,
  );
  console.log(`[${label}] saved → ${savedPath}`);
  return savedPath;
}

async function main() {
  if (!existsSync(OUTPUT_DIR)) mkdirSync(OUTPUT_DIR, { recursive: true });
  if (!existsSync(IMAGE_PATH)) throw new Error(`Image not found: ${IMAGE_PATH}`);
  if (!existsSync(WORKFLOW_PATH)) throw new Error(`Workflow not found: ${WORKFLOW_PATH}`);
  if (!existsSync(MOTION_PATH)) throw new Error(`Motion not found: ${MOTION_PATH}`);

  const motion = JSON.parse(readFileSync(MOTION_PATH, 'utf-8'));
  const promptA = `${dhee_PREAMBLE}, ${motion.motionDirective}`;
  const promptB = await buildPromptB();

  console.log('\n=== Prompt A (dhee current) ===');
  console.log(promptA);
  console.log('\n=== Prompt B (LTX-V official style via DeepSeek) ===');
  console.log(promptB);
  console.log('');

  const workflowTemplate = JSON.parse(readFileSync(WORKFLOW_PATH, 'utf-8'));

  const client = new ComfyUIClient({ outputDir: OUTPUT_DIR });
  console.log(`Uploading image ${basename(IMAGE_PATH)}...`);
  const uploaded = await client.uploadImage(IMAGE_PATH, 'input', true);
  console.log(`Uploaded as: ${uploaded.name}`);

  const pathA = await renderOne(client, workflowTemplate, promptA, uploaded.name, 'A');
  const pathB = await renderOne(client, workflowTemplate, promptB, uploaded.name, 'B');

  const sidecar = {
    image: IMAGE_PATH,
    workflow: WORKFLOW_PATH,
    scene: SCENE,
    shot: SHOT,
    promptA,
    promptB,
    outputA: pathA,
    outputB: pathB,
    ranAt: new Date().toISOString(),
  };
  const sidecarPath = join(OUTPUT_DIR, `probe_ltx_ab_${SCENE}_${SHOT}_${Date.now()}.json`);
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2));
  console.log(`\nSidecar: ${sidecarPath}`);
  console.log('Done.');
}

main().catch(err => {
  console.error('Probe failed:', err);
  process.exit(1);
});
