#!/usr/bin/env tsx
/**
 * Chain-generate shot first-frames for a project using Qwen Image Edit
 * 2511 + Multi-Angle LoRA + Lightning LoRA.
 *
 * For each scene, shot 1's first-frame comes from disk (Klein-generated
 * previously). Shots 2..N are each generated by editing the PREVIOUS
 * shot's first-frame with a Qwen Edit + Multi-Angle pass, with the
 * prompt synthesized from the shot's description + cameraWork.
 *
 * Runs against cloud Comfy by default (faster than local).
 *
 * Args:
 *   --project <path>        project dir (e.g. ".../Ruby V3")
 *   --scene N               run only scene N (default: all)
 *   --start-shot M          start chain at shot M instead of 1 (uses
 *                           existing shot M's first-frame as the base
 *                           and chains from shot M+1)
 *   --endpoint <name>       endpoint name (default: public.cloud)
 *   --dry-run               print plan without submitting
 */
import 'dotenv/config';
import { readFileSync, readdirSync, existsSync, copyFileSync } from 'node:fs';
import { join, basename } from 'node:path';
import { ComfyUIClient } from '../src/services/comfyui/ComfyUIClient.js';

function arg(name: string, dflt: string): string {
  const i = process.argv.indexOf(`--${name}`);
  return i > 0 && process.argv[i + 1] ? process.argv[i + 1]! : dflt;
}
function flag(name: string): boolean {
  return process.argv.includes(`--${name}`);
}

interface APINode { class_type: string; inputs: Record<string, unknown>; _meta?: { title?: string } }
type APIWorkflow = Record<string, APINode>;

interface ShotPlan {
  shotNumber: number;
  description?: string;
  cameraWork?: string;
  dialogue?: string;
}

// ── Cloud Qwen Edit filenames (verified against cloud catalog 2026-05-27) ──
const CLOUD_UNET            = 'qwen_image_edit_2511_bf16.safetensors';
const CLOUD_LIGHTNING_LORA  = 'Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors';
const CLOUD_MULTI_ANGLE     = 'qwen-image-edit-2511-multiple-angles-lora.safetensors';

function loadShotPlan(projectDir: string, sceneN: number, shotN: number): ShotPlan {
  const p = join(projectDir, `prompts/videos/scenes/scene_${sceneN}.shots/${shotN}.json`);
  if (!existsSync(p)) throw new Error(`Missing shot plan: ${p}`);
  const raw = JSON.parse(readFileSync(p, 'utf-8')) as Record<string, unknown>;
  return {
    shotNumber: shotN,
    description: raw['description'] as string | undefined,
    cameraWork: raw['cameraWork'] as string | undefined,
    dialogue: raw['dialogue'] as string | undefined,
  };
}

function listScenes(projectDir: string): number[] {
  const dir = join(projectDir, 'prompts/videos/scenes');
  return readdirSync(dir)
    .filter((f) => /^scene_\d+\.shots$/.test(f))
    .map((f) => parseInt(f.match(/scene_(\d+)/)![1]!, 10))
    .sort((a, b) => a - b);
}

function listShots(projectDir: string, sceneN: number): number[] {
  const dir = join(projectDir, `prompts/videos/scenes/scene_${sceneN}.shots`);
  return readdirSync(dir)
    .filter((f) => /^\d+\.json$/.test(f))
    .map((f) => parseInt(f.split('.')[0]!, 10))
    .sort((a, b) => a - b);
}

/** Find the most-recent Klein-generated first-frame for s{scene}shot{shot}. */
function findExistingFirstFrame(projectDir: string, sceneN: number, shotN: number): string | null {
  const dir = join(projectDir, 'assets/images');
  if (!existsSync(dir)) return null;
  const files = readdirSync(dir)
    .filter((f) => new RegExp(`^s${sceneN}shot${shotN}_first_frame_klein_.*\\.png$`).test(f))
    .map((f) => ({ name: f, mtime: (existsSync(join(dir, f)) ? require('node:fs').statSync(join(dir, f)).mtimeMs : 0) }))
    .sort((a, b) => b.mtime - a.mtime);
  return files.length > 0 ? join(dir, files[0]!.name) : null;
}

/** Pick the LoRA view/elevation/distance tokens from the cameraWork string. */
function mapCameraToTokens(cameraWork: string | undefined): { view: string; elevation: string; distance: string } {
  const cw = (cameraWork ?? '').toLowerCase();

  // Distance.
  let distance = 'medium shot';
  if (/close[- ]?up|tight/.test(cw)) distance = 'close-up';
  else if (/wide|establishing|long shot/.test(cw)) distance = 'wide shot';
  else if (/medium close/.test(cw)) distance = 'close-up';

  // Elevation.
  let elevation = 'eye-level shot';
  if (/low[- ]?angle/.test(cw)) elevation = 'low-angle shot';
  else if (/high[- ]?angle|overhead|down[- ]?ward/.test(cw)) elevation = 'high-angle shot';
  else if (/elevated|slightly above/.test(cw)) elevation = 'elevated shot';

  // View. Default front (continuous scene). OTS variants steer.
  let view = 'front view';
  if (/over[- ]?the[- ]?shoulder|ots/.test(cw)) view = 'back-right quarter view';
  else if (/behind|from the back|pov.*back/.test(cw)) view = 'back view';
  else if (/profile|side/.test(cw)) view = 'right side view';

  return { view, elevation, distance };
}

function buildPrompt(shot: ShotPlan): string {
  const { view, elevation, distance } = mapCameraToTokens(shot.cameraWork);
  const desc = (shot.description ?? '').trim();
  const cw = (shot.cameraWork ?? '').trim();
  return `<sks> ${view} ${elevation} ${distance}, the same setting and characters from the source image. ${desc}${cw ? ` ${cw}.` : ''} Photorealistic, same lighting and atmosphere.`;
}

function buildWorkflow(opts: {
  baseImageName: string;
  prompt: string;
  multiAngleStrength: number;
}): APIWorkflow {
  const wf: APIWorkflow = {};
  wf['UNET']         = { class_type: 'UNETLoader', inputs: { unet_name: CLOUD_UNET, weight_dtype: 'default' } };
  wf['LORA_MA']      = { class_type: 'LoraLoaderModelOnly', inputs: { lora_name: CLOUD_MULTI_ANGLE, strength_model: opts.multiAngleStrength, model: ['UNET', 0] } };
  wf['LORA_LIGHT']   = { class_type: 'LoraLoaderModelOnly', inputs: { lora_name: CLOUD_LIGHTNING_LORA, strength_model: 1.0, model: ['LORA_MA', 0] } };
  wf['MSAF']         = { class_type: 'ModelSamplingAuraFlow', inputs: { shift: 3.1, model: ['LORA_LIGHT', 0] } };
  wf['CFGN']         = { class_type: 'CFGNorm', inputs: { strength: 1.0, model: ['MSAF', 0] } };
  wf['CLIP']         = { class_type: 'CLIPLoader', inputs: { clip_name: 'qwen_2.5_vl_7b_fp8_scaled.safetensors', type: 'qwen_image', device: 'default' } };
  wf['VAE']          = { class_type: 'VAELoader', inputs: { vae_name: 'qwen_image_vae.safetensors' } };
  wf['LI']           = { class_type: 'LoadImage', inputs: { image: opts.baseImageName } };
  wf['SCALE']        = { class_type: 'FluxKontextImageScale', inputs: { image: ['LI', 0] } };
  wf['ENC']          = { class_type: 'VAEEncode', inputs: { pixels: ['SCALE', 0], vae: ['VAE', 0] } };
  wf['POS']          = { class_type: 'TextEncodeQwenImageEditPlus', inputs: { prompt: opts.prompt, clip: ['CLIP', 0], vae: ['VAE', 0], image1: ['SCALE', 0] } };
  wf['NEG']          = { class_type: 'TextEncodeQwenImageEditPlus', inputs: { prompt: '', clip: ['CLIP', 0], vae: ['VAE', 0], image1: ['SCALE', 0] } };
  wf['REF_POS']      = { class_type: 'FluxKontextMultiReferenceLatentMethod', inputs: { reference_latents_method: 'index_timestep_zero', conditioning: ['POS', 0] } };
  wf['REF_NEG']      = { class_type: 'FluxKontextMultiReferenceLatentMethod', inputs: { reference_latents_method: 'index_timestep_zero', conditioning: ['NEG', 0] } };
  wf['KS']           = { class_type: 'KSampler', inputs: { seed: Math.floor(Math.random() * 0x7fffffff), steps: 4, cfg: 1, sampler_name: 'euler', scheduler: 'simple', denoise: 1, model: ['CFGN', 0], positive: ['REF_POS', 0], negative: ['REF_NEG', 0], latent_image: ['ENC', 0] } };
  wf['DEC']          = { class_type: 'VAEDecode', inputs: { samples: ['KS', 0], vae: ['VAE', 0] } };
  wf['SAVE']         = { class_type: 'SaveImage', inputs: { images: ['DEC', 0], filename_prefix: 'qwen_chain' } };
  return wf;
}

async function main() {
  const projectDir = arg('project', '');
  const sceneArg = arg('scene', '');
  const startShot = parseInt(arg('start-shot', '1'), 10);
  const endpointName = arg('endpoint', 'public.cloud');
  const dryRun = flag('dry-run');
  if (!projectDir) {
    console.error('Usage: ruby-qwen-chain --project <path> [--scene N] [--start-shot M] [--endpoint name] [--dry-run]');
    process.exit(1);
  }

  const envKey = `ENDPOINT_${endpointName.replace(/\./g, '_')}`;
  const cloudUrl = process.env[envKey];
  if (!cloudUrl) { console.error(`${envKey} not set`); process.exit(1); }

  const scenes = sceneArg ? [parseInt(sceneArg, 10)] : listScenes(projectDir);
  console.log(`Project: ${projectDir}`);
  console.log(`Endpoint: ${endpointName} → ${cloudUrl}`);
  console.log(`Scenes: ${scenes.join(', ')}`);

  const outDir = join(projectDir, 'assets/images/qwen_chain');
  if (!existsSync(outDir)) require('node:fs').mkdirSync(outDir, { recursive: true });

  const client = new ComfyUIClient({ outputDir: outDir, baseUrl: cloudUrl });

  for (const sceneN of scenes) {
    const shots = listShots(projectDir, sceneN);
    console.log(`\n── Scene ${sceneN} (${shots.length} shots) ──`);

    // Find the base for the chain start.
    const baseShotIdx = shots.indexOf(startShot);
    if (baseShotIdx < 0) { console.error(`startShot ${startShot} not in scene ${sceneN}`); continue; }
    const baseShotN = shots[baseShotIdx]!;
    const basePath = findExistingFirstFrame(projectDir, sceneN, baseShotN);
    if (!basePath) {
      console.error(`  no existing first-frame for s${sceneN}shot${baseShotN} — skipping scene`);
      continue;
    }
    console.log(`  base: shot ${baseShotN} ← ${basename(basePath)}`);

    // Copy the base into our output dir so the chain has a clean origin.
    const baseOut = join(outDir, `s${sceneN}_shot${baseShotN}_first.png`);
    if (!existsSync(baseOut)) copyFileSync(basePath, baseOut);

    let prevPath = baseOut;
    for (let i = baseShotIdx + 1; i < shots.length; i++) {
      const shotN = shots[i]!;
      const plan = loadShotPlan(projectDir, sceneN, shotN);
      const prompt = buildPrompt(plan);
      const { view, elevation, distance } = mapCameraToTokens(plan.cameraWork);
      console.log(`  → shot ${shotN}: ${view}/${elevation}/${distance}`);
      console.log(`     desc: ${(plan.description ?? '').slice(0, 100)}…`);

      if (dryRun) continue;

      const up = await client.uploadImage(prevPath, 'input', true);
      const wf = buildWorkflow({ baseImageName: up.name, prompt, multiAngleStrength: 0.9 });

      const start = Date.now();
      const { promptId, outputs } = await client.queueAndWaitWS(wf, () => undefined);
      const hist = await client.getOutputImages(promptId);
      const all = [...outputs, ...hist].filter((o) => /\.png$/i.test(o.filename));
      if (all.length === 0) { console.error(`  ✗ no output for s${sceneN}shot${shotN}`); break; }
      const item = all[0]!;
      const targetName = `s${sceneN}_shot${shotN}_first.png`;
      const saved = await client.downloadImage(item.filename, item.subfolder ?? '', item.type ?? 'output', targetName);
      const dt = Math.floor((Date.now() - start) / 1000);
      console.log(`     ✓ ${dt}s → ${basename(saved)}`);
      prevPath = saved;
    }
  }

  console.log('\nDone.');
}

main().catch((e) => { console.error(e); process.exit(1); });
